### ISSUE TITLE
Trying to understand

### ISSUE THREAD

**Issue by shivkoirala** [pkaminski/digest-hud#13]
I have binded a simple variable to a text box and its also displayed using expression. My expression is {{Data}} , its not seen your report below. I see it in Batarang. Second what is function () { var start = perf.now(); 

Total  Watch   Work Overhead  Function
83.3% (38.9% + 11.1% + 33.3%) function () { var start = perf.now(); var ret = watchExpression.apply(this, arguments); var end = perf.now(); _digestEvents.push({ eventType: 'scope:watch', id: scopeId, watch: watchStr, time: end - start }); return ret; }

16.7% ( 0.0% +  0.0% + 16.7%) $$ng-overhead

 0.0% ( 0.0% +  0.0% +  0.0%) $evalAsync(function (){e.$$inter||!c.hasOwnProperty(a)||x(c[a])||b(c[a])})

Top 3 items account for 100.0% of 18ms of digest processing time.

**Comment by pkaminski** [comment]
Are you running Batarang at the same time as digest-hud?  I suspect Batarang is patching its own instrumentation into Angular and not propagating expression names properly, so digest-hud is stuck showing Batarang's function instead.  Try running without Batarang and see what the output is then.

**Comment by shivkoirala** [comment]
Yes its working nice. I can see this i would be disturbing you again. Congrats its a great profiler.
