### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by dlecina** [pkaminski/digest-hud#19]
Would it be too difficult to give the container div a class so we can style it? I know this isn't exactly intended for production (and I won't use it for that), but it would be useful.

**Comment by pkaminski** [comment]
Sounds like a reasonable idea and should be easy to add.  I'm no longer actively working on this component (I'm switching my apps to VueJS) but I'm happy to accept and integrate PRs if you'd like to give it a go.

**Comment by dlecina** [comment]
Thanks for integrating my PR!
